const RH_AUDIO_FREQ = 900; // hz
const LH_AUDIO_FREQ = 500; // hz
const BACKGROUND_AUDIO_FREQ = 1800; // hz
const RH_TICK_DURATION = 0.05; // sec
const LH_TICK_DURATION = 0.05; // sec
const BACKGROUND_TICK_DURATION = 0.002; // sec

export {
  RH_AUDIO_FREQ,
  LH_AUDIO_FREQ,
  BACKGROUND_AUDIO_FREQ,
  RH_TICK_DURATION,
  LH_TICK_DURATION,
  BACKGROUND_TICK_DURATION
};
