const RH_AUDIO_FREQ = 800; // hz
const LH_AUDIO_FREQ = 300; // hz
const BACKGROUND_AUDIO_FREQ = 1400; // hz
const RH_TICK_DURATION = 0.06; // sec
const LH_TICK_DURATION = 0.06; // sec
const BACKGROUND_TICK_DURATION = 0.03; // sec

export default {
  RH_AUDIO_FREQ,
  LH_AUDIO_FREQ,
  BACKGROUND_AUDIO_FREQ,
  RH_TICK_DURATION,
  LH_TICK_DURATION,
  BACKGROUND_TICK_DURATION
};
