const SET_BEAT = 'BEAT::SET_BEAT';
const SET_METRONOME_SETTING = 'METRONOME_SETTING::SET_METRONOME_SETTING';
const SET_IS_PLAYING = 'PLAYER::SET_IS_PLAYING';
const SET_PLAYER_SETTING = 'PLAYER_SETTING::SET_PLAYER_SETTING';

export {
  SET_BEAT,
  SET_METRONOME_SETTING,
  SET_IS_PLAYING,
  SET_PLAYER_SETTING
};
