const SET_BEAT = 'BEAT::SET_BEAT';
const SET_METRONOME_SETTING = 'METRONOME_SETTING::SET_METRONOME_SETTING';
const SET_PLAYER = 'PLAYER::SET_PLAYER';

export {
  SET_BEAT,
  SET_METRONOME_SETTING,
  SET_PLAYER
};
