const SET_BEAT = 'BEAT::SET_BEAT';
const SET_METRONOME_SETTING = 'METRONOME_SETTING::SET_METRONOME_SETTING';
const SET_IS_PLAYING = 'PLAYER::SET_IS_PLAYING';
const SET_IS_LOOPING = 'PLAYER::SET_IS_LOOPING';

export {
  SET_BEAT,
  SET_METRONOME_SETTING,
  SET_IS_PLAYING,
  SET_IS_LOOPING
};
