const AUDIO_FREQ_RH = 900; // hz
const AUDIO_FREQ_LH = 500; // hz
const AUDIO_FREQ_RH_LH = 700; // hz
const AUDIO_FREQ_BACKGROUND = 1800; // hz
const AUDIO_FREQ_SILENT = 0; // hz

const TICK_DURATION_RH = 0.05; // sec
const TICK_DURATION_LH = 0.05; // sec
const TICK_DURATION_RH_LH = 0.05; // sec
const TICK_DURATION_BACKGROUND = 0.001; // sec

export {
  AUDIO_FREQ_RH,
  AUDIO_FREQ_LH,
  AUDIO_FREQ_RH_LH,
  AUDIO_FREQ_BACKGROUND,
  AUDIO_FREQ_SILENT,

  TICK_DURATION_RH,
  TICK_DURATION_LH,
  TICK_DURATION_RH_LH,
  TICK_DURATION_BACKGROUND
};
